#!/bin/bash
echo "Entrer le mois:"
read mois;
if [ $mois -ge 1 -a $mois -le 12 ]; then 
echo "Mois correct!"; 
else 
echo "Mois incorrect"; exit 1
fi 
echo "Entrer l'annee:"
read annee;
if [ $annee -ge 1 -a $annee -le 2038 ]; then 
echo "Annee correct!"; 
else 
echo "Annee incorrect"; exit 1
fi
cal $mois $annee
